 ## Домашнее задание

## Задание № 1

Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [38]:
import pandas as pd

In [39]:
movies = pd.read_csv('movies.csv')
ratings = pd.read_csv('ratings.csv')

In [40]:
mix=movies.merge(ratings)

In [41]:
mix.head(50)

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1,4.0,964982703
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5,4.0,847434962
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7,4.5,1106635946
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15,2.5,1510577970
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17,4.5,1305696483
5,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,18,3.5,1455209816
6,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,19,4.0,965705637
7,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,21,3.5,1407618878
8,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,27,3.0,962685262
9,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,31,5.0,850466616
10,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,32,3.0,856736119
11,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,33,3.0,939647444
12,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,40,5.0,832058959
13,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,43,5.0,848993983
14,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,44,3.0,869251860
15,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,45,4.0,951170182
16,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,46,5.0,834787906
17,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,50,3.0,1514238116
18,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,54,3.0,830247330
19,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,57,5.0,965796031
20,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,63,5.0,1443199669
21,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,64,4.0,1161520134
22,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,66,4.0,1104643957
23,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,68,2.5,1158531426
24,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,71,5.0,864737933
25,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,73,4.5,1464196374
26,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,76,0.5,1439165548
27,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,78,4.0,1252575124
28,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,82,2.5,1084467729
29,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,86,4.0,1344082549
30,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,89,3.0,1520408314
31,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,90,3.0,856353996
32,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,91,4.0,1112713037
33,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,93,3.0,942767337
34,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,96,5.0,964772990
35,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,98,4.5,1532457849
36,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,103,4.0,1431954238
37,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,107,4.0,829322340
38,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,112,3.0,1442535639
39,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,119,3.5,1435942468
40,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,121,4.0,847656180
41,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,124,4.0,1336584336
42,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,130,3.0,832589610
43,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,132,2.0,1157921785
44,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,134,3.0,832841103
45,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,135,4.0,1009691859
46,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,137,4.0,1204859907
47,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,140,3.0,942924980
48,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,141,4.0,1513130643
49,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,144,3.5,1137323419

In [42]:
result = mix[mix.rating == 5.0 ]['title'].value_counts(normalize=True).head(1)
result

Shawshank Redemption, The (1994)    0.011581
Name: title, dtype: float64

## Задание № 2

По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [43]:
power=pd.read_csv('power.csv')

In [44]:
power[((power.country.isin(['Latvia','Lithuania','Estonia'])) & (power.category.isin([4,12,21])) 
       & ((power.year >= 2005) & (power.year <= 2010)) & (power.quantity > 0))].quantity.sum()

240580.0

## Задание № 3

Выберите страницу любого сайта с табличными данными. Импортируйте таблицы в pandas dataframe.
Примеры страниц (необязательно брать именно эти):  
https://fortrader.org/quotes  
https://www.finanz.ru/valyuty/v-realnom-vremeni

In [48]:
page = 'https://ru.myfin.by/currency'
df = pd.read_html(page, encoding='utf-8')
pd.DataFrame(df[0])

       Валюта  Покупка  Продажа  Курс ЦБ 26.01.2021
0      Доллар    75.41    71.99             74.8569
1        Евро    91.51    91.58             91.1458
2        Юань    11.63     8.47             11.5575
3        Фунт   102.65    83.10            102.6064
4    Тенге100    12.19    19.55             17.7938
5  Бел. рубль    26.37    32.64             29.2513
6     Йена100    72.60    73.00             72.1617
7       Франк    90.22    74.76             84.5077
8      Злотый    19.95    20.60             20.0866
9    Гривна10    20.20    26.00             26.5898